### PR TITLE
[WIP] Reorganize and refactor

### PR DESCRIPTION
**Pull request by paolochiodi**
WIP refresh of the store to adhere to new stores structure and make it work with newer versions of seneca and node (builds on top of #19)

### CODE REVIEW

**Comment by guyellis** [comment]
After setting up MySQL I tested this with `npm test` and out-the-box without any changes the tests don't pass on Node versions 0.10.40, 0.12.7 and 4.0.0

**Comment by mcdonnelldean** [comment]
@paolochiodi @colmharte Is this ok to be merged?

**Comment by paolochiodi** [comment]
Mostly. IIRC package.json should point to the now-released version of seneca store test, and README needs some updates

**Comment by mcdonnelldean** [comment]
Awesome, I'm going push the new doc after lunch for this so. Just wanted to make sure :dancer:

**Comment by mcdonnelldean** [comment]
Readme updated as of #21

**Comment by mcdonnelldean** [comment]
@paolochiodi Can you check the conflicts on this?

**Comment by paolochiodi** [comment]
@mcdonnelldean I'll give a look to this, but I'm wondering if it's worth the effort to release a version now or if it's better to wait that this https://github.com/rjrodger/seneca-store-test/pull/18 gets merged and the new version of seneca-store-test gets published

**Comment by paolochiodi** [comment]
rebased to fix conflicts

**Comment by ckiss** [comment]
@paolochiodi I'll do some maintenance work on this. can you please solve the conflicts again? thanks :)

**Comment by ckiss** [comment]
@paolochiodi any news on this? can you please rebase to fix conflicts?

**Comment by paolochiodi** [comment]
I'm sorry, no.
I will be able to look at this this week, but not before Wednesday or Thursday

**Comment by ckiss** [comment]
@paolochiodi no worries. This week is fine. thanks

**Comment by mihaidma** [comment]
@paolochiodi @ckiss i started working today on the mysql plugin. I will fix also this PR

**Comment by paolochiodi** [comment]
thanks @mihaidma

**Comment by mcdonnelldean** [comment]
@mihaidma @paolochiodi What's the story with this PR? is it still valid? It needs resolving if so.

**Comment by mihaidma** [comment]
@mcdonnelldean I am currently working on postgres but by tomorrow I will switch to mysql. Mysql will use seneca-standard-query for query generation and all this PR will be probably cancelled. I will not close it until I look over the fixes not to lose any info.

**Comment by mcdonnelldean** [comment]
@mihaidma awesome stuff :+1:

**Comment by mihaidma** [comment]
the mysql was unified with the postgres one (and reusing the postgres code), this won't be merged as the code is not the same anymore

**Pull request closed without merging**
